
name: Upstream Issue Checker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Runs at 00:00 every Sunday.

permissions:
  issues: write
  
jobs:
  check_upstream_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Check and Comment on Upstream Issues
        uses: kewisch/action-bugzilla-upstream@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
